# Generated by Django 4.2.19 on 2025-05-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0002_alter_filial_options_remove_filial_cidade_and_more'),
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='setor',
            name='filiais',
            field=models.ManyToManyField(related_name='setores', to='filial.filial'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
