# Generated by Django 4.2.19 on 2025-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default='Guanambi', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(default='Bahia', max_length=100),
        ),
    ]
