# Generated by Django 4.2.19 on 2025-05-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('setor', '0001_initial'),
        ('pessoa', '0002_pessoa_cidade_pessoa_data_pessoa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='filial.filial'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='setor.setor'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
