# Generated by Django 4.2.19 on 2025-05-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_alter_setor_options_remove_setor_descricao_and_more'),
        ('pessoa', '0003_pessoa_filial_pessoa_setor_alter_pessoa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='filial',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='setor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='setor.setor'),
            preserve_default=False,
        ),
    ]
