# Generated by Django 4.2.19 on 2025-05-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={},
        ),
        migrations.RemoveField(
            model_name='filial',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='estado',
        ),
        migrations.AlterField(
            model_name='filial',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
